# Generated by Django 4.1.2 on 2022-10-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_product', models.FileField(upload_to='uploads/excel')),
            ],
            options={
                'verbose_name': 'Mahsulohlar Excel Fayli ',
                'verbose_name_plural': 'Mahsulohlar Excel Fayllari ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_product', models.FileField(upload_to='uploads/excel')),
                ('product_id', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('option_Name', models.CharField(blank=True, max_length=200)),
                ('hidden', models.CharField(blank=True, max_length=200)),
                ('weight', models.CharField(blank=True, max_length=200)),
                ('prepaymentPercent', models.CharField(blank=True, max_length=200)),
                ('bonusesPercent', models.CharField(blank=True, max_length=200)),
                ('hidden_btn', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
    ]
