# Generated by Django 4.1.2 on 2022-10-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='excel_product',
            field=models.FileField(blank=True, null=True, upload_to='uploads/excel'),
        ),
    ]
